### ISSUE TITLE
DefineInstallationPaths should not use cache variables

### ISSUE THREAD

**Issue by eile** [BlueBrain/MVDTool#14]
... just normal variables, so I can change CMAKE_INSTALL_PREFIX.

What is the use case anyways? Most of these paths can be used relative with the install() commands.

**Comment by adevress** [comment]
> What is the use case anyways? Most of these paths can be used relative with the install() commands.

The use case is to be able to override them at compile time on the same model that the autotools. (e.g --sysconfig, --libdir, docdir, etc , etc ) and match the specific standard paths of your OS ( lib/lib64, versionned docdir, sysconfig or /usr or /usr/local ) 

 I did not write this file nor the name variable, they are standard cmake variable used and define by most of the packaging tools including rpm (/etc/rpm/macros.cmake ) and the deb helpers.

However you are right, this is annoying to get them cache. I would switch this to something like "IF NOT DEFINE THEN SET(blalba )

**Comment by eile** [comment]
CMAKE_INSTALL_PREFIX is the absolute path, and there can be overridable lib/share sub-paths?

Also they should be prefixed by the project name, otherwise subproject trample on each other's variables.

Last, but not least, why not set() without cache?

**Comment by adevress** [comment]
> CMAKE_INSTALL_PREFIX is the absolute path, and there can be overridable lib/share sub-paths?

Yes, excepted that they should not be only subpath, you can have situation where $...CMAKE_INSTALL_PREFIX=/usr and  $SYSCONFIG=/etc or $RUNDIR=/var  It's not always a subpath. 

> Last, but not least, why not set() without cache? 
Agree, we need to fix that.  That's what I meant in my previous comment.

> Also they should be prefixed by the project name, otherwise subproject trample on each other's variables.

The one that are defined now are conventions. I can however use the prefixed version when they are defined to have compatibility with subproject if you wish.

**Comment by eile** [comment]
> Yes, excepted that they should not be only subpath

And we need this?

**Comment by eile** [comment]
> The one that are defined now are conventions

Up to you... Just pointing out trouble for you guys.

**Comment by adevress** [comment]
> And we need this?

That's not about needing it, that's about respecting conventions.

> Up to you... Just pointing out trouble for you guys. 

They are not our conventions, the naming scheme is now part of the official cmake 3.0 modules release.
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

This file is just there to provide cmake 2.8 compat.
