### ISSUE TITLE
Querying properties of cell subsets in mvd3 circuit is very slow in debug mode 

### ISSUE THREAD

**Issue by hernando** [BlueBrain/MVDTool#45]
I don't have the hard data, but it can take in the order of minutes. If needed I can provide data.

In release is not that slow, but it could be faster nonetheless. A potential solution may be to simply load always the whole datasets and apply a linear filter afterwards.

**Comment by adevress** [comment]
Hi Juan,

Can you precise what do you mean by "cell subsets" ? Are you loading it one cell per one cell ?

How it is designed now is that : one query = at least one I/O operation. If you load cell by cell, you will get disastrous performances.

The API is designed to allo you to load by "range" but should not be used to load one per one.

**Comment by hernando** [comment]
I'm using brain the operation I was testing is something like this: circuit.positions(circuit.gids[0::300])
In principle this gets translated into a single IO operation with the range spanned by all the gids.

I just sampled with the debugger where the program was spending so much time and it hit inside MVDTool. I haven't dug any further. There's another function in the C++ side of brain that could be responsible for the bottleneck, but I'd be surprised as it's just a linear filtering.

**Comment by hernando** [comment]
I'll close the issue because I didn't write the client code to MVDTool and maybe I drew my conclusion too fast.

**Comment by adevress** [comment]
@hernando 

One thing that might help you Juan:
MVDTool does an heavy usage of Boost.UBLAS matrix that makes an heavy usage of assert. Enabling -DNDEBUG improve generally a lot the performance. This is enabled by default in Release but not in Debug.

**Comment by hernando** [comment]
Sure, the issue was specific to debug mode.
