### ISSUE TITLE
Compilation with HighFive 2.2

### ISSUE THREAD

**Issue by NadirRoGue** [BlueBrain/MVDTool#77]
Hello,

I am trying to compile MVDTool, however I am running into some trouble with HIghFive. After compiling and installing HighFive and libsonata, I run the cmake command, getting the following error regarding HighFive:

```
nadir@nadirlaptop:~/Projects/MVDTool/build$ rm -rf * && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/nadir/Projects/h5install;/home/nadir/Projects/sonatainstall"
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
CMake Error at /home/nadir/Projects/h5install/share/HighFive/CMake/HighFiveConfig.cmake:28 (target_compile_features):
  Cannot specify compile features for imported target "HighFive".
Call Stack (most recent call first):
  CMakeLists.txt:50 (find_package)


HIGHFIVE 2.2: (Re)Detecting Highfive dependencies (HIGHFIVE_USE_INSTALL_DEPS=NO)
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   serialization
-- Configuring incomplete, errors occurred!
See also "/home/nadir/Projects/MVDTool/build/CMakeFiles/CMakeOutput.log"
```

Boost and HDF5 are installed at system level, and I am specifying HighFive and sonata at cmake prefix path level. Did I executed the wrong command? Do I have to specify any other option I might be missing?

As a side note, I think it would be interesting to list the hard dependencies (Boost, HDF5, HighFive and sonata) in the README.md file

Thank you for your time.

Regards,
Nadir.

**Comment by NadirRoGue** [comment]
Hi, Im using cmake version 3.10.2

**Comment by ferdonline** [comment]
Ok, I think I see it now. From 3.9 we use compiler features to set the standard, instead of throwing a user error.
Please check if, in the meantime, by setting CMAKE_CXX_STANDARD, you avoid the error. 
We shall correct this

**Comment by NadirRoGue** [comment]
Worked flawlessly. Thank you very much.

Closing.
