### ISSUE TITLE
Unhandled exception when mecombo file does not exists / is empty.

### ISSUE THREAD

**Issue by NadirRoGue** [BlueBrain/MVDTool#86]
Hello,

When trying to retrieve the layer information from an mvd3 circuit, we feed the mecombo file path from the CircuitConfig/BlueConfig to mvd. Sometimes, the generated circuit has the entry in the config file, but the file does not exists, or is an empty string.

After feeding this to mvdtool, it crashes reporting a wrong layout of the file (wrong number of columns), however the real reason is that the file does not exists.

https://github.com/BlueBrain/MVDTool/blob/098c197e3782b52b243f1247217c5f330e260221/include/mvdtool/bits/tsv_misc.hpp#L66

**Comment by mgeplf** [comment]
Note: the reason that an mecombo doesn't exist is that as a scientist builds a circuit, they like to look at the placement without having emodels yet.

**Comment by matz-e** [comment]
Couldn't whatever writes the `CircuitConfig` put a placeholder file there, containing just the header?

**Comment by ferdonline** [comment]
Uh, old issue. IMO these cases should be handled by throwing an informative exception
