### ISSUE TITLE
Poor performance with large METypeCombo

### ISSUE THREAD

**Issue by ferdonline** [BlueBrain/MVDTool#96]
Some recent simulations have a very large number of METypes.

With recent circuits, counting 9M+ entries in the MeCombo, parsing and fetching data takes a huge amount of memory and is very slow, in the order of minutes.

This should be investigated since it is likely that, with such memory footprint, we can improve the fetching.
We likely need to change the `max_load_factor` and do a `reserve`.

**Comment by ferdonline** [comment]
@iomaganaris Can I assign this to you since you implemented most of the TSV reading?

**Comment by iomaganaris** [comment]
Hello @ferdonline 

Thanks for reporting this. I will have a look once time permits.
